In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_Y = iris.target
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_Y_train = iris_Y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_Y_test = iris_Y[indices[-10:]]

In [2]:
np.unique(iris_Y)

array([0, 1, 2])

In [3]:
class MyClassifier:
    def __init__ (self):
        print("this a majority class classifier")
    
    def fit(self, X, Y):
        from operator import itemgetter
        c = dict()
        for item in Y:
            c[item] = c.get(item, 0) + 1
        x = max(c.items(), key=itemgetter(1))
        self.Y = x[0]
        return self

    def predict(self, X):
        return [self.Y for i in range(len(X))]

In [4]:
mySuperClassifier = MyClassifier()
mySuperClassifier.fit(iris_X_train, iris_Y_train)


this a majority class classifier


In [5]:
iris_Y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [6]:
iris_Y_predict = mySuperClassifier.predict(iris_X_test)
iris_Y_predict

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [7]:
accuracy = accuracy_score(iris_Y_test, iris_Y_predict)
print('%.3f'%accuracy)

0.200


In [8]:
#2. justify why the evaluation results using the new classifier are correct
#Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(iris_Y_test, iris_Y_predict, labels=[0, 1, 2])

array([[0, 0, 4],
       [0, 0, 4],
       [0, 0, 2]])

In [9]:
'''Accuracy is defined as the fraction of instances that are correctly classified.
accuracy = sum(diag) / n, where: 
diag: number of correctly classified instances per class  
n: number of instances
(0+0+2)/10 = 0.200
'''

'Accuracy is defined as the fraction of instances that are correctly classified.\naccuracy = sum(diag) / n, where: \ndiag: number of correctly classified instances per class  \nn: number of instances\n(0+0+2)/10 = 0.200\n'

In [10]:
#3. OPTIONAL: create another classifier with higher performance than the majority class classifier
#SVC
from sklearn.svm import SVC
svc = SVC(kernel="linear", C=0.025)
c1 = svc.fit(iris_X_train, iris_Y_train)
accuracy1 = accuracy_score(iris_Y_test, c1.predict(iris_X_test))
print('%.3f'%accuracy1)

1.000


In [11]:
from sklearn.ensemble import BaggingClassifier
bag = BaggingClassifier(base_estimator=svc,
                         n_estimators=500, 
                         max_samples=1.0, 
                         max_features=1.0, 
                         bootstrap=True, 
                         bootstrap_features=False, 
                         n_jobs=1, 
                         random_state=1)
bag = bag.fit(iris_X_train, iris_Y_train)
accuracyBagging = accuracy_score(iris_Y_test, bag.predict(iris_X_test))
print('%.3f'%accuracyBagging)

1.000
